// generated by create bookmarklet command
CmdUtils.makeBookmarkletCommand({
  name: "pinboard",
  icon: "http://pinboard.in/favicon.ico",
  homepage: "http://jason.karns.name/",
  author: { name: "Jason Karns" },
  description: "Save to Pinboard",
  url: "javascript:if(document.getSelection){s=document.getSelection();}else{s='';};document.location='https://pinboard.in/add?next=same&url='+encodeURIComponent(location.href)+'&description='+encodeURIComponent(s)+'&title='+encodeURIComponent(document.title)",
});
