// generated by create bookmarklet command
CmdUtils.makeBookmarkletCommand({
  name: "cuethat",
  icon: "http://cuethat.com/favicon.ico",
  homepage: "http://jason.karns.name/",
  author: { name: "Jason Karns" },
  description: "Add  movies to your Netflix queue",
  url: "javascript:var%20d=document,z=d.createElement('scr'+'ipt'),b=d.body;try{if(!b)throw(0);d.title='(Posting...)%20'+d.title;z.setAttribute('src','http://cuethat.com/bookmarklet');b.appendChild(z);}catch(e){alert('Please%20wait%20until%20the%20page%20has%20loaded.');}void(0)"
});